### ISSUE TITLE
Payments display sort stuck on Payment type

### ISSUE THREAD

**Issue by johnanastasio17** [fearless359/simpleinvoices#18]
When viewing Payments screen, payments are listed A-Z by type (cash, then check, then electronic, etc). Can not change column sort to "by date", "by number", "by customer", etc. Can not reverse any of the columns (including payment type that it is stuck on) from A-Z to Z-A
Columns are fully sortable when accessing database in phpMyadmin.
No errors when entering a new payment, data is writing to database. 
I do notice that the first payment recorded since switching from si2011 to fearless359 version has _NULL_ under "online_payment_id" column, no previous entries have this.
Using Fearless359/simpleinvoices, on Wampserver64, Win10 64bit
Same behavior with Firefox and Chrome

**Comment by tmtisfree** [comment]
This is because column names are improperly referenced in $validFields array in the 'xml.php' file and in flexigrid in the 'manage.js.php' file.

Open both 'modules/payments/manage.js.php' and 'modules/payments/xml.php' files.

In 'manage.js.php', replace the 'biller' string with the string 'bname', and replace the 'customer' string with the string 'cname'. Save.

In 'xml.php', search for the '$validFields' array. Replace the 'biller' string with the string 'bname', and replace the 'customer' string with the string 'cname'. Save.

Reload (beware to also edit the payment_quickview extension if you happen to use it, as it has the same files with the same problem).

Both columns are now sortable.

**Comment by fearless359** [comment]
Just upload fix for column sort on payments and invoices flex grid. This includes grids when payments extension is enabled.
